# Non-Negative Matric Factorization

Let's repeat the topic modeling task from the previous lecture, but this time, we will use NMF instead of LDA.

## Read this before proceeding further
https://medium.com/@cmukesh8688/tf-idf-vectorizer-scikit-learn-dbc0244a911a

## Data

We will be using articles scraped from NPR (National Public Radio), obtained from their website [www.npr.org](http://www.npr.org)

In [1]:
import pandas as pd

In [2]:
npr = pd.read_csv('npr.csv')

In [9]:
len(npr)

11992

In [10]:
npr

Article
0      In the Washington of 2016, even when the polic...
1        Donald Trump has used Twitter  —   his prefe...
2        Donald Trump is unabashedly praising Russian...
3      Updated at 2:50 p. m. ET, Russian President Vl...
4      From photography, illustration and video, to d...
...                                                  ...
11987  The number of law enforcement officers shot an...
11988    Trump is busy these days with victory tours,...
11989  It’s always interesting for the Goats and Soda...
11990  The election of Donald Trump was a surprise to...
11991  Voters in the English city of Sunderland did s...

[11992 rows x 1 columns]

In [3]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

## Preprocessing

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer

**`max_df`**` : float in range [0.0, 1.0] or int, default=1.0`<br>
When building the vocabulary ignore terms that have a document frequency strictly higher than the given threshold (corpus-specific stop words). If float, the parameter represents a proportion of documents, integer absolute counts. This parameter is ignored if vocabulary is not None.

**`min_df`**` : float in range [0.0, 1.0] or int, default=1`<br>
When building the vocabulary ignore terms that have a document frequency strictly lower than the given threshold. This value is also called cut-off in the literature. If float, the parameter represents a proportion of documents, integer absolute counts. This parameter is ignored if vocabulary is not None.

In [6]:
tfidf = TfidfVectorizer(max_df=0.95, min_df=2, stop_words='english')

For better understanding : https://stackoverflow.com/questions/50906210/confused-with-the-return-result-of-tfidfvectorizer-fit-transform

In [7]:
dtm = tfidf.fit_transform(npr['Article'])

In [31]:
print(dtm)

  (0, 162)	0.024207779726177357
  (0, 436)	0.057426739142936806
  (0, 604)	0.02813089107375169
  (0, 650)	0.02653652777634086
  (0, 1288)	0.022444232597226593
  (0, 1434)	0.028763633914840988
  (0, 1489)	0.023797160985101373
  (0, 1608)	0.03226897967994957
  (0, 1610)	0.020693641331932494
  (0, 1613)	0.07253465437685631
  (0, 1632)	0.025308912294465642
  (0, 1674)	0.01910359684823228
  (0, 1762)	0.017698767416640195
  (0, 1884)	0.025404296400493534
  (0, 1932)	0.027002284256125594
  (0, 1993)	0.044568871723068636
  (0, 2045)	0.07533311505887272
  (0, 2060)	0.0383433531113439
  (0, 2084)	0.015039386128760875
  (0, 2093)	0.04883763812854993
  (0, 2347)	0.03491292226818417
  (0, 2437)	0.05672110592908613
  (0, 2491)	0.04202580292018094
  (0, 2525)	0.028380087248686597
  (0, 2689)	0.016700219215567812
  :	:
  (11991, 52783)	0.15232527696882306
  (11991, 52786)	0.032524386440987
  (11991, 52788)	0.03858014866091516
  (11991, 52977)	0.05145632144946742
  (11991, 53014)	0.009862718553798772
 

<i><span style="color: blue;">Tf-idf is one of the best metrics to determine how significant a term is to a text in a series or a corpus. tf-idf is a weighting system that assigns a weight to each word in a document based on its term frequency (tf) and the reciprocal document frequency (tf) (idf). The words with higher scores of weight are deemed to be more significant.</color></span></i>

In [42]:
print(tfidf.get_feature_names_out()[1884]) #0.025404296400493534 - tf-idf score of a given token in a given document
print(tfidf.get_feature_names_out()[52783])# 0.15232527696882306 voted - this token seems to be the more significant

adviser
voted


## NMF

In [43]:
from sklearn.decomposition import NMF

In [44]:
nmf_model = NMF(n_components=7,random_state=42)

In [45]:
# This can take awhile, we're dealing with a large amount of documents!
nmf_model.fit(dtm)

NMF(n_components=7, random_state=42)

## Displaying Topics

In [46]:
len(tfidf.get_feature_names_out())

54777

In [26]:
import random

In [27]:
for i in range(10):
    random_word_id = random.randint(0,54776)
    print(tfidf.get_feature_names_out()[random_word_id])

counterfeiting
ameliorate
surry
smuggled
generic
ditched
stoves
preordained
susilo
hermitage


In [47]:
for i in range(10):
    random_word_id = random.randint(0,54776)
    print(tfidf.get_feature_names_out()[random_word_id])

anupam
oss
mciver
bigot
ekeroth
calls
recruiter
morehouse
muscat
drowsy


In [48]:
len(nmf_model.components_)

7

In [49]:
nmf_model.components_

array([[0.00000000e+00, 2.51270507e-01, 0.00000000e+00, ...,
        1.71376078e-03, 2.39241571e-04, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 8.23172575e-02, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 3.12287576e-02, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [5.90615701e-03, 0.00000000e+00, 1.50483058e-03, ...,
        7.06176596e-04, 5.86173445e-04, 6.90910657e-04],
       [4.01955802e-03, 5.31379095e-02, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [50]:
len(nmf_model.components_[0])

54777

In [51]:
single_topic = nmf_model.components_[0]

In [52]:
# Returns the indices that would sort this array.
single_topic.argsort()

array([    0, 27208, 27206, ..., 36283, 54692, 42993], dtype=int64)

In [61]:
# Word least representative of this topic
print(single_topic[0])
print(single_topic[36283])

0.0
0.4981534088085525


In [54]:
# Word most representative of this topic
single_topic[42993]

2.016202325291806

In [62]:
# Top 10 words for this topic:
single_topic.argsort()[-10:]

array([14441, 36310, 53989, 52615, 47218, 53152, 19307, 36283, 54692,
       42993], dtype=int64)

In [63]:
top_word_indices = single_topic.argsort()[-10:]

In [65]:
for index in top_word_indices:
    print(tfidf.get_feature_names_out()[index])

disease
percent
women
virus
study
water
food
people
zika
says


These look like medical/health articles perhaps... Let's confirm by using .transform() on our vectorized articles to attach a label number. But first, let's view all the 10 topics found.

In [67]:
for index,topic in enumerate(nmf_model.components_):
    print(f'THE TOP 15 WORDS FOR TOPIC #{index}')
    print([tfidf.get_feature_names_out()[i] for i in topic.argsort()[-15:]])
    print('\n')

THE TOP 15 WORDS FOR TOPIC #0
['new', 'research', 'like', 'patients', 'health', 'disease', 'percent', 'women', 'virus', 'study', 'water', 'food', 'people', 'zika', 'says']


THE TOP 15 WORDS FOR TOPIC #1
['gop', 'pence', 'presidential', 'russia', 'administration', 'election', 'republican', 'obama', 'white', 'house', 'donald', 'campaign', 'said', 'president', 'trump']


THE TOP 15 WORDS FOR TOPIC #2
['senate', 'house', 'people', 'act', 'law', 'tax', 'plan', 'republicans', 'affordable', 'obamacare', 'coverage', 'medicaid', 'insurance', 'care', 'health']


THE TOP 15 WORDS FOR TOPIC #3
['officers', 'syria', 'security', 'department', 'law', 'isis', 'russia', 'government', 'state', 'attack', 'president', 'reports', 'court', 'said', 'police']


THE TOP 15 WORDS FOR TOPIC #4
['primary', 'cruz', 'election', 'democrats', 'percent', 'party', 'delegates', 'vote', 'state', 'democratic', 'hillary', 'campaign', 'voters', 'sanders', 'clinton']


THE TOP 15 WORDS FOR TOPIC #5
['love', 've', 'don', 'al

### Attaching Discovered Topic Labels to Original Articles

In [68]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.float64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [69]:
dtm.shape

(11992, 54777)

In [70]:
len(npr)

11992

In [72]:
topic_results = nmf_model.transform(dtm)

In [73]:
topic_results.shape

(11992, 7)

In [74]:
topic_results[0]

array([0.        , 0.12079653, 0.00139891, 0.05915242, 0.01519226,
       0.        , 0.        ])

In [75]:
topic_results[0].round(2)

array([0.  , 0.12, 0.  , 0.06, 0.02, 0.  , 0.  ])

In [76]:
topic_results[0].argmax()

1

This means that our model thinks that the first article belongs to topic #1.

### Combining with Original Data

In [77]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [78]:
topic_results.argmax(axis=1)

array([1, 1, 1, ..., 0, 4, 3], dtype=int64)

In [79]:
npr['Topic'] = topic_results.argmax(axis=1)

In [80]:
npr.head(10)

Article  Topic
0  In the Washington of 2016, even when the polic...      1
1    Donald Trump has used Twitter  —   his prefe...      1
2    Donald Trump is unabashedly praising Russian...      1
3  Updated at 2:50 p. m. ET, Russian President Vl...      3
4  From photography, illustration and video, to d...      6
5  I did not want to join yoga class. I hated tho...      5
6  With a   who has publicly supported the debunk...      0
7  I was standing by the airport exit, debating w...      0
8  If movies were trying to be more realistic, pe...      0
9  Eighteen years ago, on New Year’s Eve, David F...      5